require("luasnip.loaders.from_snipmate").lazy_load({paths = "~/.config/nvim/snippets"})
require("luasnip.loaders.from_vscode").lazy_load({})

require("luasnip").filetype_extend("typescript", { "tsdoc" })
require("luasnip").filetype_extend("javascript", { "jsdoc" })
require("luasnip").filetype_extend("lua", { "luadoc" })
require("luasnip").filetype_extend("python", { "pydoc" })
require("luasnip").filetype_extend("rust", { "rustdoc" })
require("luasnip").filetype_extend("cs", { "csharpdoc" })
require("luasnip").filetype_extend("java", { "javadoc" })
require("luasnip").filetype_extend("c", { "cdoc" })
require("luasnip").filetype_extend("cpp", { "cppdoc" })
require("luasnip").filetype_extend("php", { "phpdoc" })
require("luasnip").filetype_extend("kotlin", { "kdoc" })
require("luasnip").filetype_extend("ruby", { "rdoc" })
require("luasnip").filetype_extend("sh", { "shelldoc" })
require("luasnip").filetype_extend("shell", { "shelldoc" })
require("luasnip").filetype_extend("verilog", { "verilogdoc" })
require("luasnip").filetype_extend("vhdl", { "vhdldoc" })
require("luasnip").filetype_extend("make", { "make" })
require("luasnip").filetype_extend("cmake", { "cmake" })
require("luasnip").filetype_extend("dockerfile", { "dockerfile" })
require("luasnip").filetype_extend("docker-compose", { "docker-compose" })
require("luasnip").filetype_extend("markdown", { "markdown" })
require("luasnip").filetype_extend("html", { "html" })
require("luasnip").filetype_extend("css", { "css" })
require("luasnip").filetype_extend("yaml", { "yaml" })
