require("colorizer").setup({
	filetypes = { "*" },
	buftypes = {},
	user_commands = true,
	lazy_load = false,
	options = {
		parsers = {
			css = false,
			css_fn = false,
			names = {
				enable = true,
				lowercase = true,
				camelcase = true,
				uppercase = false,
				strip_digits = false,
				custom = false,
				extra_word_chars = "-",
			},
			hex = {
				default = true,
				rgb = true,
				rgba = true,
				rrggbb = true,
				rrggbbaa = false,
				hash_aarrggbb = false,
				aarrggbb = false,
				no_hash = false,
			},
			rgb = { enable = false },
			hsl = { enable = false },
			oklch = { enable = false },
			hwb = { enable = false },
			lab = { enable = false },
			lch = { enable = false },
			css_color = { enable = false },
			tailwind = {
				enable = false,
				update_names = false,
				lsp = {
					enable = false,
					disable_document_color = true,
				},
			},
			sass = {
				enable = false,
				parsers = { css = true },
				variable_pattern = "^%$([%w_-]+)",
			},
			xterm = { enable = false },
			xcolor = { enable = false },
			hsluv = { enable = false },
			css_var_rgb = { enable = false },
			css_var = {
				enable = false,
				parsers = { css = true },
			},
			custom = {},
		},
		display = {
			mode = "background",
			background = {
				bright_fg = "#000000",
				dark_fg = "#ffffff",
			},
			virtualtext = {
				char = "■",
				position = "eol",
				hl_mode = "foreground",
			},
			priority = {
				default = 150,
				lsp = 200,
			},
			disable_document_color = true,
		},
		hooks = {
			should_highlight_line = false,
			should_highlight_color = false,
			transform_color = false,
			on_attach = false,
			on_detach = false,
		},
		always_update = false,
		debounce_ms = 0,
	},
})
